AWSTemplateFormatVersion: '2010-09-09'
Description: AWS EC2 for Deep Learning Environment with ElasticIP

Parameters:
  ImageId:
    Description: Amazon Machine Image (AMI)
    Type:        String
    Default:     ami-06c414f3ba4a59e2f
    
  EC2InstanceType:
    Description: EC2 instance type on which IDE runs
    Type:        String
    Default:     g4dn.xlarge
  
  KeyName:
    Description: Keypair name
    Type:        String
    Default:     my-key
  
  SecurityGroupIds:
    Description:  inbound/outbound settings(Port 22 needs to be open)
    Type:         String
    Default:      sg-0b8540e42b30c9c95

  SubnetId:
    Description:  Public subnet in vpc
    Type:         String
    Default:      subnet-0c436a37fd2d96fed
  
  VolumeSize:
    Description:  root volume size
    Type:         String
    Default:      100

Resources:
  NewKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: !Ref "KeyName"

  Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      AvailabilityZone: "ap-northeast-1a"
      ImageId: !Ref "ImageId"
      InstanceType: !Ref "EC2InstanceType"
      KeyName: !Ref "NewKeyPair"
      SecurityGroupIds: 
        - !Ref "SecurityGroupIds"
      SubnetId: !Ref "SubnetId"
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeType: gp3
            VolumeSize: !Ref "VolumeSize"
            DeleteOnTermination: 'false'
            Encrypted: 'false'
      UserData: 
        Fn::Base64: |
          #!/bin/sh
          sudo apt-get update && sudo apt-get -y upgrade
          sudo apt-get -y install nodejs
          sudo /usr/local/bin/pip install --upgrade autopep8
          sudo apt -y install python2
          sudo reboot

  ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc

  ElasticIPAssociate:
    Type: AWS::EC2::EIPAssociation
    Properties: 
      AllocationId: !GetAtt ElasticIP.AllocationId
      InstanceId: !Ref Instance